---
services: docker

env:
  - distro: centos7
  - distro: centos6
  - distro: ubuntu1604
  - distro: ubuntu1404
  - distro: ubuntu1204
  - distro: fedora27
  - distro: debian9
  - distro: debian8

script:
  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/6419f0a8f1b2002f6315df8a2e9d3959fdedc4cd/ansible-role-test.sh
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh ${distro}

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
